
server:
  port: 9999
spring:
  application:
    name: "member_post"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://np.sangwon97.com:3306/the_k
    username: thek
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

mybatis:
  mapper-locations: 
  - classpath:mapper/*.xml
  type-aliases-package: com.sangwon97.member_post.vo
  configuration:
    map-underscore-to-camel-case: true